directionBtn="//button[@id='searchbox-directions']"
sourceField="(//input[@class='tactile-searchbox-input'])[3]"
destinationField="(//input[@class='tactile-searchbox-input'])[4]"
carBtn="//div[@data-travel_mode='0']"
cycleBtn="//div[@data-travel_mode='1']"
flightBtn="//div[@data-travel_mode='4']"
walkBtn="//div[@data-travel_mode='2']"
carFirstResultHours="(//div[@class='section-directions-trip-duration delay-light']/span)[1]"
walkBicycleFirstResultHours="//div[@class='section-directions-trip-duration']"
walkFirstResultMiles="//div[@class='section-directions-trip-distance section-directions-trip-secondary-text']"
ferryMessage="(//h6[@class='notice-headline'])[1]"
flightResultLink="(//a[@class='section-directions-trip-flight-search-link'])[1]"
fromDate="(//div[@class='gws-flights__flex-filler gws-flights__ellipsize gws-flights-form__input-target'])[1]"
toDate="(//div[@class='gws-flights__flex-filler gws-flights__ellipsize gws-flights-form__input-target'])[2]"
firstAvailDate="(//calendar-day[@class='gws-travel-calendar__day'])[1]"
availDate="(//calendar-day[@class='gws-travel-calendar__day'])"
nextMonthSelectionBtn="//div[@class='njjicd rSFy9b']"
nextMonthSelectionBtnDisabled="//div[@class='njjicd rSFy9b gws-travel-calendar__disabled']"